title: "Code & Thoughts"
author: Bruno Abinader
email: brunoabinader@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Made with :heart: from Finland.

baseurl: "" # the subpath of your site, e.g. /blog

url: "https://brunoabinader.github.io" # the base hostname & protocol for your site

theme: minima

permalink: pretty

plugins:
  - jemoji # User-defined
  - github-pages
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-relative-links
  - jekyll-titles-from-headings

# social links
twitter_username: brunoabinader
github_username: brunoabinader
linkedin_username: brunoabinader

disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  shortname: https-brunoabinader-github-io

google_analytics: G-NRF47WEFP9

show_excerpts: false # set to false to remove excerpts on the homepage

# Github immutable options

markdown: kramdown
lsi: false
safe: true
#source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
